# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokencache',
            name='expiresOn',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
