# Generated by Django 2.0.5 on 2018-05-02 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSeatingArrangement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('userId', models.CharField(max_length=255, null=True)),
                ('classId', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'classroom_seating_arranements',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('tenantId', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('isAdminConsented', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o365UserId', models.CharField(max_length=255, null=True)),
                ('o365Email', models.CharField(max_length=255, null=True)),
                ('favoriteColor', models.CharField(max_length=255, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Organization')),
                ('user', models.OneToOneField(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='TokenCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o365UserId', models.CharField(max_length=255, null=True)),
                ('refreshToken', models.TextField(null=True)),
                ('accessToken', models.TextField(null=True)),
                ('expiresOn', models.DateTimeField(null=True)),
                ('resource', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'token_cache',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('o365UserId', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
    ]
