# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdUsers',
        ),
        migrations.AddField(
            model_name='users',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
