# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170401_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='color',
            new_name='favoriteColor',
        ),
        migrations.AddField(
            model_name='users',
            name='o365Email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='o365UserId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
