# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170405_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
