# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170405_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSeatingArrangements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('userId', models.CharField(max_length=255, null=True)),
                ('classId', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'classroomseating',
            },
        ),
        migrations.CreateModel(
            name='TokenCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=255, null=True)),
                ('refreshToken', models.CharField(max_length=255, null=True)),
                ('accessToken', models.CharField(max_length=255, null=True)),
                ('expiresOn', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tokencache',
            },
        ),
    ]
