# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_classroomseatingarrangements_tokencache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenCache',
        ),
    ]
